# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

cacheFolder: .yarn/cache

checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs
