# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

nodeLinker: node-modules

# To update Yarn, run:
# `yarn set version stable` (This will download the latest version of Yarn and store it in .yarn/releases)
# Then update the reference below to the new file name in .yarn/releases
yarnPath: .yarn/releases/yarn-4.6.0.cjs