cacheFolder: .yarn/cache

checksumBehavior: ignore

compressionLevel: 0

enableGlobalCache: false

httpTimeout: 2147483647

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.0.cjs

enableStrictSsl: false
