nodeLinker: node-modules

packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-proposal-decorators@*":
    dependencies:
      "@babel/core": "*"
  babel-loader@*:
    dependencies:
      "@babel/core": "*"
  intl-unofficial-duration-unit-format@*:
    dependencies:
      intl-messageformat: "*"
enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.2.2.cjs
