nodeLinker: node-modules
packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-proposal-decorators@*":
    dependencies:
      "@babel/core": "*"
  "intl-unofficial-duration-unit-format@*":
    dependencies:
      "intl-messageformat": "*"
  "babel-loader@*":
    dependencies:
      "@babel/core": "*"
