---
language: node_js
node_js:
  - "6"

sudo: false

addons:
  apt:
    packages:
      - xvfb

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g grunt-cli"

install:
  - npm install -g bower
  - npm install
  - bower install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm test
