# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Share desktop artifacts folder
  config.vm.synced_folder "../../../out/release", "/vagrant-desktop-app", create: true,  owner: "vagrant", group: "vagrant", automount: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y
    # sudo apt-get install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11 curl
    # Setup localhost ssh
    # yes | ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/id_rsa -q -N ""
    # cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    # Add vagrant to administrator group
    sudo usermod -aG sudo vagrant
    # Add vagrant to shared folder
    sudo usermod -aG vboxsf vagrant
  SHELL

  # Setup for testing desktop
  config.vm.provision "test", type: "shell", inline: <<-SHELL
    # Install desktop GUI
    sudo apt-get install -y --no-install-recommends lubuntu-desktop
    # Setup boundary cli
    sudo apt-get install docker.io -y
    sudo groupadd docker
    sudo usermod -aG docker vagrant
    sudo apt-get install -y unzip
    cd /home/vagrant/Desktop
    curl https://releases.hashicorp.com/boundary/0.5.0/boundary_0.5.0_linux_amd64.zip -o boundary-cli.zip
    unzip boundary-cli.zip
    # Restart
    sudo shutdown -r now
  SHELL

  # Setup for developing desktop
  config.vm.provision "development", type: "shell", inline: <<-SHELL
    sudo apt-get remove cmdtest
    sudo apt-get install -y npm git

    git clone https://github.com/hashicorp/boundary-ui.git /home/vagrant/Desktop/boundary-ui
    sudo npm install yarn
    # Setup node 12 source
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Install boundary-ui dependencies
    cd /home/vagrant/Desktop/boundary-ui
    yarn install
  SHELL

  config.vm.post_up_message = "Login using username/password: vagrant/vagrant.\nBoundary Desktop: /media/sf_vagrant-boundary-desktop-app.\nBoundary CLI: /home/vagrant/Desktop."
end
