#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn compliance:licenses
npx lint-staged


while read line; do
  if grep "SPDX-License-Identifier: BUSL-1.1" $line; then
    sed -i '/SPDX-License-Identifier: BUSL-1.1/d' $line
    sed -i '/Copyright (c) HashiCorp, Inc./d' $line
  fi
done

copywrite headers