name: Trigger OSS to Enterprise Merge
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  trigger-oss-merge:
    # Run this only on merge events in OSS repo
    if: ${{ github.event.pull_request.merged && github.repository == 'hashicorp/boundary-ui' }}
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    steps:
      - name: Trigger Merge
        env:
          GIT_REF: ${{ github.ref_name }}
          GIT_SHA: ${{ github.sha }}
          GH_PAT: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          GIT_ACTOR: ${{ github.actor }}
        run: |
          curl -H "Authorization: token $GH_PAT" \
            -H 'Accept: application/json' \
            -d "{\"event_type\": \"oss-merge\", \"client_payload\": {\"git-ref\": \"${GIT_REF}\", \"git-sha\": \"${GIT_SHA}\", \"git-actor\": \"${GIT_ACTOR}\" }}" \
            "https://api.github.com/repos/hashicorp/boundary-ui-enterprise/dispatches"