name: test workflow yarn upgrade
on: pull_request
jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --immutable
