name: Testing Cache
on: pull_request
jobs:
  
  job1:
    name: job 1 (test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
      - run: yarn run compliance:licenses
  
  job2:
    name: job 2 (test)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
      - run: yarn lint:addons-api