# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

checksumBehavior: ignore

enableGlobalCache: false

yarnPath: ../../../.yarn/releases/yarn-4.4.0.cjs

cacheFolder: ../../../.yarn/cache

compressionLevel: mixed

httpTimeout: 2147483647

nodeLinker: node-modules

httpRetry: 10
