# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

checksumBehavior: ignore

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

cacheFolder: .yarn/cache

compressionLevel: mixed
